name: CI
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '24'
      - run: yarn install --frozen-lockfile
      - run: yarn prepare
      - run: yarn eslint src/Logger.ts src/NetworkRequestInfo.ts src/XHRInterceptor.ts
      - run: yarn typescript
      - run: yarn prettier
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '24'
      - run: yarn install --frozen-lockfile
      - run: yarn test --coverage
